In [1]:
import pandas as pd
import numpy as np

In [3]:
viagra_spam = {'viagra': [1,0,0,0,0,0,0,0,1,1,1,0,0,1,0,0,0,0,0,1],
               'spam': [1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,1,1]}

In [5]:
df = pd.DataFrame(viagra_spam, columns = ['viagra', 'spam'])
np_data = df.values
np_data

array([[1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 0],
       [1, 1],
       [1, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 1],
       [1, 1]], dtype=int64)

In [8]:
sum((np_data[:,0]==1)& (np_data[:,1]==1)) / 20

0.15

In [9]:
p_viagra = sum(np_data[:,0]==1) / len(np_data)

In [10]:
p_spam = sum(np_data[:,1]==1) / len(np_data)

In [11]:
p_v_cap_s = sum((np_data[:,0]==1)& (np_data[:,1]==1)) / len(np_data)

In [12]:
p_n_v_cap_s = sum((np_data[:,0]==0)& (np_data[:,1]==1)) / len(np_data)

In [13]:
p_v_cap_s / p_viagra

0.5

In [14]:
p_n_v_cap_s / (1-p_viagra)

0.2142857142857143

In [15]:
df = pd.read_csv('fraud.csv',sep=',')

In [16]:
df

ID  History  CoApplicant Accommodation  Fraud
0    1  current         none           own   True
1    2     paid         none           own  False
2    3     paid         none           own  False
3    4     paid    guarantor          rent   True
4    5  arrears         none           own  False
5    6  arrears         none           own   True
6    7  current         none           own  False
7    8  arrears         none           own  False
8    9  current         none          rent  False
9   10     none         none           own   True
10  11  current  coapplicant           own  False
11  12  current         none           own   True
12  13  current         none          rent   True
13  14     paid         none           own  False
14  15  arrears         none           own  False
15  16  current         none           own  False
16  17  arrears  coapplicant          rent  False
17  18  arrears         none          free  False
18  19  arrears         none           own  False
19  20     paid         none           own  False

In [17]:
del df["ID"]
Y_data = df.pop("Fraud")
Y_data = Y_data.values
x_df = pd.get_dummies(df)

In [18]:
x_df

History_arrears  History_current  History_none  History_paid  \
0                 0                1             0             0   
1                 0                0             0             1   
2                 0                0             0             1   
3                 0                0             0             1   
4                 1                0             0             0   
5                 1                0             0             0   
6                 0                1             0             0   
7                 1                0             0             0   
8                 0                1             0             0   
9                 0                0             1             0   
10                0                1             0             0   
11                0                1             0             0   
12                0                1             0             0   
13                0                0             0             1   
14                1                0             0             0   
15                0                1             0             0   
16                1                0             0             0   
17                1                0             0             0   
18                1                0             0             0   
19                0                0             0             1   

    CoApplicant_coapplicant  CoApplicant_guarantor  CoApplicant_none  \
0                         0                      0                 1   
1                         0                      0                 1   
2                         0                      0                 1   
3                         0                      1                 0   
4                         0                      0                 1   
5                         0                      0                 1   
6                         0                      0                 1   
7                         0                      0                 1   
8                         0                      0                 1   
9                         0                      0                 1   
10                        1                      0                 0   
11                        0                      0                 1   
12                        0                      0                 1   
13                        0                      0                 1   
14                        0                      0                 1   
15                        0                      0                 1   
16                        1                      0                 0   
17                        0                      0                 1   
18                        0                      0                 1   
19                        0                      0                 1   

    Accommodation_free  Accommodation_own  Accommodation_rent  
0                    0                  1                   0  
1                    0                  1                   0  
2                    0                  1                   0  
3                    0                  0                   1  
4                    0                  1                   0  
5                    0                  1                   0  
6                    0                  1                   0  
7                    0                  1                   0  
8                    0                  0                   1  
9                    0                  1                   0  
10                   0                  1                   0  
11                   0                  1                   0  
12                   0                  0                   1  
13                   0                  1                   0  
14                   0                  1                   0  
15                   0                

In [22]:
x_data = x_df.values

In [23]:
x_data

array([[0, 1, 0, 0, 0, 0, 1, 0, 1, 0],
       [0, 0, 0, 1, 0, 0, 1, 0, 1, 0],
       [0, 0, 0, 1, 0, 0, 1, 0, 1, 0],
       [0, 0, 0, 1, 0, 1, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 1, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 1, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 1, 0, 0, 0, 1, 0, 1, 0],
       [0, 1, 0, 0, 1, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 1, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 1, 0, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 1, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1, 1, 0, 0],
       [1, 0, 0, 0, 0, 0, 1, 0, 1, 0],
       [0, 0, 0, 1, 0, 0, 1, 0, 1, 0]], dtype=uint8)

In [24]:
Y_data

array([ True, False, False,  True, False,  True, False, False, False,
        True, False,  True,  True, False, False, False, False, False,
       False, False])

In [28]:
P_Y_True = sum(Y_data==True) / len(Y_data)
P_Y_False = 1 - P_Y_True
print(P_Y_True,P_Y_False)

0.3 0.7


In [29]:
ix_Y_True = np.where(Y_data)
ix_Y_False = np.where(Y_data==False)
ix_Y_True, ix_Y_False

((array([ 0,  3,  5,  9, 11, 12], dtype=int64),),
 (array([ 1,  2,  4,  6,  7,  8, 10, 13, 14, 15, 16, 17, 18, 19],
        dtype=int64),))

In [30]:
p_x_y_true = (x_data[ix_Y_True].sum(axis=0)) / sum(Y_data==True)
p_x_y_false = (x_data[ix_Y_False].sum(axis=0)) / sum(Y_data==False)

In [31]:
print(p_x_y_true, p_x_y_false)

[0.16666667 0.5        0.16666667 0.16666667 0.         0.16666667
 0.83333333 0.         0.66666667 0.33333333] [0.42857143 0.28571429 0.         0.28571429 0.14285714 0.
 0.85714286 0.07142857 0.78571429 0.14285714]


In [32]:
x_test = [0,1,0,0,0,1,0, 0,1,0]
p_y_true_test = P_Y_True + p_x_y_true.dot(x_test)
p_y_false_test = P_Y_False + p_x_y_false.dot(x_test)


In [34]:
p_y_true_test, p_y_false_test

(1.6333333333333333, 1.7714285714285714)

In [35]:
y_example_text = ["Sports","Not sports","Sports", 
"Sports","Not sports"]
y_example = [1 if c=="Sports" else 0 for c in y_example_text ]


In [36]:
text_example = ["A great game game","The The election was over", 
                "Very clean game match", "A clean but forgettable game game", 
                "It was a close election", ]

In [40]:
from sklearn.feature_extraction.text import CountVectorizer
countvect_example = CountVectorizer()
X_example = countvect_example.fit_transform(text_example)
countvect_example.get_feature_names()

['but',
 'clean',
 'close',
 'election',
 'forgettable',
 'game',
 'great',
 'it',
 'match',
 'over',
 'the',
 'very',
 'was']

In [41]:
type(countvect_example.get_feature_names())

list

In [47]:
from sklearn.naive_bayes import BernoulliNB

In [48]:
clf = BernoulliNB(alpha=1, binarize=0)
clf.fit(X_example, y_example)

BernoulliNB(alpha=1, binarize=0, class_prior=None, fit_prior=True)

In [50]:
clf.class_log_prior_

array([-0.91629073, -0.51082562])

In [51]:
import seaborn as sns
import matplotlib.pyplot as plt

In [52]:
import re
%matplotlib inline

In [2]:
from sklearn.datasets import fetch_20newsgroups

In [3]:
news = fetch_20newsgroups(subset='all')

In [6]:
news_df = pd.DataFrame({'News' : news.data, 'Target' : news.target})

In [9]:
import re

In [7]:
 def data_cleansing(df):
    delete_email = re.sub(r'\b[\w\+]+@[\w]+.[\w]+.[\w]+.[\w]+\b', ' ', df)
    delete_number = re.sub(r'\b|\d+|\b', ' ',delete_email)
    delete_non_word = re.sub(r'\b[\W]+\b', ' ',delete_number)
    cleaning_result =' '.join(delete_non_word.split())
    return cleaning_result

In [10]:
news_df.loc[:,'News'] = news_df['News'].apply(data_cleansing)

In [12]:
news_df.head()

News  Target
0  From Mamatha Devineni Ratnam Subject Pens fans...      10
1  From Matthew B Lawson Subject Which high perfo...       3
2  From hilmi Hilmi Eren Subject Re ARMENIA SAYS ...      17
3  From Guy Dawson Subject Re IDE vs SCSI DMA and...       3
4  From Alexander Samuel McDiarmid Subject driver...       4

In [13]:
!pip install nltk

In [16]:
from nltk import stem
stmmer = stem.SnowballStemmer("english")


In [18]:
from sklearn.feature_extraction.text import CountVectorizer
import nltk

In [19]:
enlish_stemmer = nltk.stem.SnowballStemmer("english")
class StemmedCountVectorizer(CountVectorizer):
    def build_analyzer(self):
        analyzer = super(StemmedCountVectorizer,self).build_analyzer()
        return lambda doc: (enlish_stemmer.stem(w) for w in analyzer(doc))

In [20]:
from sklearn.naive_bayes import MultinomialNB, BernoulliNB,GaussianNB

In [23]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [21]:
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.pipeline import make_pipeline

In [24]:
enlish_stemmer = nltk.stem.SnowballStemmer("english")
class StemmedTfidfVectorizer(TfidfVectorizer):
    def build_analyzer(self):
        analyzer = super(StemmedTfidfVectorizer,self).build_analyzer()
        return lambda doc: (enlish_stemmer.stem(w) for w in analyzer(doc))

In [25]:
vectorizer = [CountVectorizer(), TfidfVectorizer(),StemmedCountVectorizer(), StemmedTfidfVectorizer()]

In [26]:
algorithms = [MultinomialNB(), LogisticRegression()]
pipelines = []

In [27]:
import itertools
for case in list(itertools.product(vectorizer,algorithms)):
    pipelines.append(make_pipeline(*case))

In [28]:
pipelines

[Pipeline(memory=None,
          steps=[('countvectorizer',
                  CountVectorizer(analyzer='word', binary=False,
                                  decode_error='strict',
                                  dtype=<class 'numpy.int64'>, encoding='utf-8',
                                  input='content', lowercase=True, max_df=1.0,
                                  max_features=None, min_df=1,
                                  ngram_range=(1, 1), preprocessor=None,
                                  stop_words=None, strip_accents=None,
                                  token_pattern='(?u)\\b\\w\\w+\\b',
                                  tokenizer=None, vocabulary=None)),
                 ('multinomialnb',
                  MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))],
          verbose=False), Pipeline(memory=None,
          steps=[('countvectorizer',
                  CountVectorizer(analyzer='word', binary=False,
                                  decode_error='

In [29]:
ngrams_params = [(1,1),(1,3)]
stopword_params = ["english"]
lowercase_params = [True, False]
max_df_params = np.linspace(0.4, 0.6, num=6)
min_df_params = np.linspace(0.0, 0.0, num=1)

In [30]:
attributes = {"ngram_range":ngrams_params, "max_df":max_df_params,"min_df":min_df_params, 
              "lowercase":lowercase_params,"stop_words":stopword_params}

In [31]:
attributes

{'ngram_range': [(1, 1), (1, 3)],
 'max_df': array([0.4 , 0.44, 0.48, 0.52, 0.56, 0.6 ]),
 'min_df': array([0.]),
 'lowercase': [True, False],
 'stop_words': ['english']}

In [32]:
vectorizer_names = ["countvectorizer","tfidfvectorizer","stemmedcount vectorizer","stemmedtfidfvectorizer"]

In [33]:
vectorizer_params_dict = {}

In [35]:
for vect_name in vectorizer_names:
    vectorizer_params_dict[vect_name] = {}
for key, value in attributes.items():
    param_name = vect_name + "__" + key
    vectorizer_params_dict[vect_name][param_name] = value

In [36]:
algorithm_names = ["multinomialnb", "logisticregression"]

In [37]:
algorithm_params_dict = {}
alpha_params = np.linspace(1.0, 1.0, num=1)
for i in range(1):
    algorithm_params_dict[algorithm_names[i]] = {algorithm_names[i]+ "__alpha" : alpha_params}
c_params = [0.1, 5.0, 7.0, 10.0, 15.0, 20.0, 100.0]

In [38]:
algorithm_params_dict[algorithm_names[1]] = [{"logisticregression__multi_class" : ["multinomial"],"logisticregression__solver" : ["saga"],
                                              "logisticregression__penalty" : ["l1"],"logisticregression__C" : c_params},
                                             {"logisticregression__multi_class" : ["ovr"],"logisticregression__solver" : ['liblinear'],
                                              "logisticregression__penalty" : ["l2"],"logisticregression__C" : c_params}]

In [39]:
pipeline_params= []
for case in list(itertools.product(vectorizer_names, algorithm_names)):
    vect_params = vectorizer_params_dict[case[0]].copy()
    algo_params = algorithm_params_dict[case[1]]
    if isinstance(algo_params, dict):
        vect_params.update(algo_params)
        pipeline_params.append(vect_params)
    else:
        temp = []
        for param in algo_params:
            vect_params.update(param)
            temp.append(vect_params)
        pipeline_params.append(temp)

In [40]:
from sklearn.preprocessing import LabelEncoder

In [41]:
X_data = news_df.loc[:, 'News'].tolist()
y_data = news_df['Target'].tolist()
y = LabelEncoder().fit_transform(y_data)

In [42]:
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, accuracy_score

In [43]:
scoring = ['accuracy']
estimator_results = []

In [44]:
for i, (estimator, params) in enumerate(zip(pipelines,pipeline_params)):
    n_jobs = -1
    gs_estimator = GridSearchCV(refit="accuracy", estimator=estimator,param_grid=params, 
                                scoring=scoring, cv=5, verbose=1,n_jobs=n_jobs)
    print(gs_estimator)
    gs_estimator.fit(X_data, y)
    estimator_results.append(gs_estimator)

GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=Pipeline(memory=None,
                                steps=[('countvectorizer',
                                        CountVectorizer(analyzer='word',
                                                        binary=False,
                                                        decode_error='strict',
                                                        dtype=<class 'numpy.int64'>,
                                                        encoding='utf-8',
                                                        input='content',
                                                        lowercase=True,
                                                        max_df=1.0,
                                                        max_features=None,
                                                        min_df=1,
                                                        ngram_range=(1, 1),
                                 

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done   2 out of   5 | elapsed:   21.8s remaining:   32.7s
[Parallel(n_jobs=-1)]: Done   5 out of   5 | elapsed:   23.4s finished


GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=Pipeline(memory=None,
                                steps=[('countvectorizer',
                                        CountVectorizer(analyzer='word',
                                                        binary=False,
                                                        decode_error='strict',
                                                        dtype=<class 'numpy.int64'>,
                                                        encoding='utf-8',
                                                        input='content',
                                                        lowercase=True,
                                                        max_df=1.0,
                                                        max_features=None,
                                                        min_df=1,
                                                        ngram_range=(1, 1),
                                 

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.


KeyboardInterrupt: 