In [1]:
import numpy as np
rand_data = np.random.randn(10)

In [2]:
print(rand_data)

[ 0.33672784  0.90669588 -1.13719138  0.60404982 -0.98984835 -0.53470684
 -0.98160834  1.82627969  0.48359245 -0.32562783]


In [3]:
result = np.where(rand_data >0, "a", rand_data)
print(result)

['a' 'a' '-1.1371913768974609' 'a' '-0.9898483486243516'
 '-0.5347068366992325' '-0.9816083384362199' 'a' 'a'
 '-0.32562783081804847']


In [4]:
result = np.where(rand_data >0, True, rand_data)
print(result)

[ 1.          1.         -1.13719138  1.         -0.98984835 -0.53470684
 -0.98160834  1.          1.         -0.32562783]


In [5]:
rand_data.sum()

0.18836294151199173

In [6]:
rand_data.mean()

0.018836294151199175

In [7]:
np.mean(rand_data)

0.018836294151199175

In [8]:
rand_data = np.random.randn(2,5)
rand_data

array([[ 6.36197678e-01, -7.58489244e-04, -4.84566577e-01,
         8.66548958e-01,  8.59329475e-01],
       [-2.20367500e-01, -1.32312994e+00, -7.32158387e-01,
        -1.34373468e+00, -5.78947108e-01]])

In [9]:
rand_data = np.random.randint(2,9,20)

In [10]:
rand_data

array([4, 6, 2, 5, 3, 8, 2, 6, 4, 3, 2, 6, 3, 3, 6, 8, 8, 7, 5, 5])

In [11]:
print(np.unique(rand_data,return_counts=True))

(array([2, 3, 4, 5, 6, 7, 8]), array([3, 4, 2, 3, 4, 1, 3], dtype=int64))


In [12]:
rand_data = np.random.randint(1,45,(450,6))

In [13]:
print(rand_data)

[[ 7 30 11  8 16 41]
 [14 17  9 29  7  5]
 [18  4 23 10 34 17]
 ...
 [23 43 23 43 18 30]
 [16 12 35 23 43 24]
 [10 29 35 31 33  2]]


In [14]:
np.unique(rand_data,return_counts=True)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 36, 37, 38, 39, 40, 41, 42, 43, 44]),
 array([67, 67, 61, 70, 67, 71, 68, 65, 34, 62, 67, 68, 69, 54, 65, 68, 52,
        62, 48, 51, 47, 65, 74, 52, 54, 75, 64, 58, 58, 47, 56, 62, 58, 58,
        68, 66, 60, 62, 65, 67, 59, 55, 74, 60], dtype=int64))

In [15]:
rand_data = np.random.randint(1,45,(45000,6))
np.unique(rand_data,return_counts=True)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 36, 37, 38, 39, 40, 41, 42, 43, 44]),
 array([6152, 6243, 6004, 6174, 6223, 6051, 6173, 6197, 6010, 6015, 6103,
        6162, 6151, 6234, 6251, 6207, 6142, 6176, 6214, 6237, 6047, 6185,
        6142, 6096, 6258, 6152, 5944, 6228, 6129, 5957, 6197, 6194, 6122,
        6060, 6071, 6172, 6234, 6054, 6027, 6119, 6130, 6194, 6040, 6129],
       dtype=int64))

In [16]:
np.unique(rand_data,return_counts=True)[1]/6000

array([1.02533333, 1.0405    , 1.00066667, 1.029     , 1.03716667,
       1.0085    , 1.02883333, 1.03283333, 1.00166667, 1.0025    ,
       1.01716667, 1.027     , 1.02516667, 1.039     , 1.04183333,
       1.0345    , 1.02366667, 1.02933333, 1.03566667, 1.0395    ,
       1.00783333, 1.03083333, 1.02366667, 1.016     , 1.043     ,
       1.02533333, 0.99066667, 1.038     , 1.0215    , 0.99283333,
       1.03283333, 1.03233333, 1.02033333, 1.01      , 1.01183333,
       1.02866667, 1.039     , 1.009     , 1.0045    , 1.01983333,
       1.02166667, 1.03233333, 1.00666667, 1.0215    ])

In [17]:
import pandas as pd
ss = pd.Series(['a','b']*2)
ss.describe()

count     4
unique    2
top       a
freq      2
dtype: object

In [18]:
ss.isin(['b'])

0    False
1     True
2    False
3     True
dtype: bool

In [19]:
from google.colab import drive

ModuleNotFoundError: No module named 'google'

In [20]:
df

NameError: name 'df' is not defined